// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuuK07ZLbEnk4KZ6WeuZMHUdOJ0alLgD4',
    appId: '1:713206219196:web:5b28a6a7a489829ff8ebb9',
    messagingSenderId: '713206219196',
    projectId: 'egyptian-legal-assistant',
    authDomain: 'egyptian-legal-assistant.firebaseapp.com',
    storageBucket: 'egyptian-legal-assistant.firebasestorage.app',
    measurementId: 'G-THKPCHTTHC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoRaWq5XNO0n2if5r4sp2MDl8XEdw3ssU',
    appId: '1:713206219196:android:a1ee7ca12db389aff8ebb9',
    messagingSenderId: '713206219196',
    projectId: 'egyptian-legal-assistant',
    storageBucket: 'egyptian-legal-assistant.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDIAZED0NppG_RmOqjCbLJgw1GYE7pr_k',
    appId: '1:713206219196:ios:f9189380053ce6caf8ebb9',
    messagingSenderId: '713206219196',
    projectId: 'egyptian-legal-assistant',
    storageBucket: 'egyptian-legal-assistant.firebasestorage.app',
    iosBundleId: 'com.example.egyptianLegalAssistantApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDIAZED0NppG_RmOqjCbLJgw1GYE7pr_k',
    appId: '1:713206219196:ios:f9189380053ce6caf8ebb9',
    messagingSenderId: '713206219196',
    projectId: 'egyptian-legal-assistant',
    storageBucket: 'egyptian-legal-assistant.firebasestorage.app',
    iosBundleId: 'com.example.egyptianLegalAssistantApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuuK07ZLbEnk4KZ6WeuZMHUdOJ0alLgD4',
    appId: '1:713206219196:web:6bd9f9b6de876887f8ebb9',
    messagingSenderId: '713206219196',
    projectId: 'egyptian-legal-assistant',
    authDomain: 'egyptian-legal-assistant.firebaseapp.com',
    storageBucket: 'egyptian-legal-assistant.firebasestorage.app',
    measurementId: 'G-TT3XHP8FPQ',
  );
}
